include: package:lints/recommended.yaml

linter:
  rules:
    - public_member_api_docs
    - sort_constructors_first
    - prefer_single_quotes
    - always_declare_return_types
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
